// Builds app/static/js/lang/{en,es,pt,uk}.js from tools/i18n/translations.txt and checks
// that every key used in the code (tools/i18n/keys.json, from extract.mjs) is translated.
//   node tools/i18n/extract.mjs && node tools/i18n/build.mjs
import fs from 'node:fs';
import path from 'node:path';
const here = path.dirname(new URL(import.meta.url).pathname);
const out = path.resolve(here, '../../js/lang');
const keys = JSON.parse(fs.readFileSync(path.join(here, 'keys.json'), 'utf8'));
const LANGS = [['en', 'EN'], ['es', 'ES'], ['pt', 'PT'], ['uk', 'UK']];
const tables = Object.fromEntries(LANGS.map(([c]) => [c, {}]));
const seen = new Set();
const bad = [];
const unspace = (s) => s.replace(/␣/g, ' ');
for (const [i, line] of fs.readFileSync(path.join(here, 'translations.txt'), 'utf8').split('\n').entries()) {
  if (!line.trim() || line.startsWith('#') && !line.startsWith('#{')) continue;
  const parts = line.split(' ‖ ');
  const plural = parts[0].startsWith('#{');
  const key = unspace(plural ? parts[0].slice(1) : parts[0]);
  if (parts.length !== 5) { bad.push(`line ${i + 1}: ${parts.length} columns: ${parts[0].slice(0, 40)}`); continue; }
  if (seen.has(key)) bad.push(`line ${i + 1}: duplicate key ${key.slice(0, 40)}`);
  seen.add(key);
  LANGS.forEach(([code], n) => {
    const v = unspace(parts[n + 1]);
    tables[code][key] = plural ? v.split(' / ') : v;
  });
}
const used = new Set(keys.map((k) => k.key));
for (const k of used) if (!seen.has(k)) bad.push(`MISSING translation: ${JSON.stringify(k)}  (${keys.find((x) => x.key === k).where})`);
for (const k of seen) if (!used.has(k)) bad.push(`unused row: ${JSON.stringify(k)}`);
// every placeholder of the source must survive in every language
for (const k of used) {
  const ph = (k.match(/\{\w+\}/g) || []).sort().join();
  for (const [code] of LANGS) {
    const v = tables[code][k];
    if (v === undefined) continue;
    const s = Array.isArray(v) ? v[0] : v;
    const got = (s.match(/\{\w+\}/g) || []).sort().join();
    if (ph !== got && !(Array.isArray(v) && ph === '{n}')) bad.push(`placeholder mismatch [${code}] ${k.slice(0, 40)}: ${ph} vs ${got}`);
  }
}
for (const [code, name] of LANGS) {
  const body = Object.entries(tables[code]).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n');
  fs.writeFileSync(path.join(out, `${code}.js`), `// Generated by tools/i18n/build.mjs from translations.txt — edit that file, not this one.\nexport const ${name} = {\n${body}\n};\n`);
}
console.log(`${seen.size} rows, ${used.size} keys used`);
console.log(bad.length ? bad.join('\n') : 'OK: every key is translated');
if (bad.length) process.exit(1);
