// Cold-start helper: rewrites the block between <!-- preload:start --> and <!-- preload:end --> in index.html.
//  - every css/tx/*.css as its own <link> (parallel; an @import chain is fetched one level at a time)
//  - <link rel=modulepreload> for the whole static import graph of js/app.js (parallel instead of waterfall)
//   node tools/build-preload.mjs [--check]
import fs from 'node:fs';
import path from 'node:path';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..', 'app', 'static');
const indexPath = path.join(root, 'index.html');
const html = fs.readFileSync(indexPath, 'utf8');
// Order matters; skin.css is last on purpose: mods restyle everything through it.
const order = ['tokens', 'layout', 'avatar', 'dock', 'post', 'thread', 'settings', 'viewer', 'stories', 'profile', 'auth', 'mods', 'onboarding', 'light', 'icons-android', 'skin'].map((n) => `css/tx/${n}.css`);
for (const f of order) if (!fs.existsSync(path.join(root, f))) { console.error('missing ' + f); process.exit(1); }

const seen = new Set();
const walk = (rel) => {
  if (seen.has(rel)) return;
  seen.add(rel);
  const src = fs.readFileSync(path.join(root, rel), 'utf8');
  for (const m of src.matchAll(/(?:^|[\s;}])(?:import|export)\s[^'"`;]*?from\s*'(\.[^']+)'|(?:^|[\s;}])import\s*'(\.[^']+)'/g)) {
    const spec = m[1] || m[2];
    walk(path.posix.normalize(path.posix.join(path.posix.dirname(rel), spec)));
  }
};
walk('js/app.js');
const mods = [...seen].filter((f) => f !== 'js/app.js');

const block = [
  '<!-- preload:start (generated by tools/build-preload.mjs) -->',
  ...order.map((f) => `  <link rel="stylesheet" href="${f}">`),
  ...mods.map((f) => `  <link rel="modulepreload" href="${f}">`),
  '  <!-- preload:end -->',
].join('\n');

const next = html.replace(/<!-- preload:start[\s\S]*?<!-- preload:end -->/, block);
if (next === html && !/preload:start/.test(html)) { console.error('markers missing in index.html'); process.exit(1); }
if (process.argv.includes('--check')) {
  if (next !== html) { console.error('index.html preload block is out of date: run `node tools/build-preload.mjs`'); process.exit(1); }
  console.log(`preload ok (${order.length} css, ${mods.length} modules)`);
} else {
  fs.writeFileSync(indexPath, next);
  console.log(`preload: ${order.length} css, ${mods.length} modules`);
}
